### ISSUE TITLE
2.0.28 Not Working

### ISSUE THREAD

**Issue by adit-s** [klutchell/dnscrypt-proxy#2] opened 2019-10-23 22:47 UTC
Hello. I've been using your docker container, dnscrypt-proxy, for about a month now and it's worked fine. I'm mapping to an external configuration folder - -v /path/to/config:/config. I did not have the -c /config/dnscrypt-proxy.toml option and it worked as expected until the latest image.
Do you have any suggestions as to what may have "broken" it?

--
In the mean time I'll go back to 2.0.27.

Thanks,
Adit Sood

**Comment by adit-s** [comment] 2019-10-23 22:49
In case you need it, I create the container with a bash script:
docker create \
  --name=dnscrypt2 \
  --restart=always \
  -e PGID=1000 -e PUID=1000  \
  -p 5053:5053/udp \
  -v /home/pi/docker-dir/dnscrypt/config/:/config:rw \
  klutchell/dnscrypt-proxy

**Comment by klutchell** [comment] 2019-10-23 23:06
Hey there, I see what you've probably run into. Recently there was a change to the way config files are loaded in the container and it means (for now at least) you'll need to specify the config file path when running. Here's the change as it would appear in your bash script.

```bash
docker create
--name=dnscrypt2
--restart=always
-e PGID=1000 -e PUID=1000
-p 5053:5053/udp
-v /home/pi/docker-dir/dnscrypt/config/:/config:rw
klutchell/dnscrypt-proxy -c /config/dnscrypt-proxy.toml
```

Notice that `-c /config/dnscrypt-proxy.toml` has been added to your run command.

The README has been updated with new usage examples but it's not immediately obvious for existing users. I may end up rolling back the changes if more folks have trouble with it.

**Comment by adit-s** [comment] 2019-10-23 23:32
Thanks for the quick response. I started by reviewing the instructions on docker hub and did try with the -c option as you suggested, but got an error where the container keeps restarting.
The log shows 
standard_init_linux.go:211: exec user process caused "no such file or directory"

I'm not sure why or how to trouble shoot it. Any ideas?

**Comment by klutchell** [comment] 2019-10-23 23:40
May I ask what platform you're running on? ARM or x86_64? If you're on Linux can you provide the output of `uname -a`?

I'll try to reproduce in my own environment.

**Comment by adit-s** [comment] 2019-10-23 23:42
It's a Raspberry Pi 3B.

Output of uname -a is:
Linux pi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by klutchell** [comment] 2019-10-23 23:55
Hmm, it's running on amd64 just fine so it's must be specific to ARM. Perhaps docker is pulling the wrong manifest.
Could you check the output of `docker inspect --format='{{.Architecture}}' klutchell/dnscrypt-proxy` for me?

Also you could try running `docker pull --platform=linux/arm/v7 klutchell/dnscrypt-proxy` and see if the result of the previous command changes.

I'll spin up one of my pi3's for testing.

**Comment by adit-s** [comment] 2019-10-24 00:04
Hi. The output of 
`docker inspect --format='{{.Architecture}}' klutchell/dnscrypt-proxy`
responds `arm`.

For the `docker pull --platform=linux/arm/v7 klutchell/dnscrypt-proxy`
I get the message `"--platform" is only supported on a Docker daemon with experimental features enabled`

**Comment by klutchell** [comment] 2019-10-24 01:47
I found the problem, it seems to be affecting all platforms except amd64 so I didn't encounter it in my tests. I've pushed a quick fix for now that will roll out to 2.0.28 on docker hub over the next hour.

Thanks for bringing this to my attention!

**Comment by adit-s** [comment] 2019-10-24 20:42
Hi. I spun up a new container with the updated image and started it using the same method as described above (without the -c option for the image which had the problem). It works, but the status shows "unhealthy". This was not the status with the previous image.

The logs (from Portainer) show:
> [2019-10-24 20:28:34] [NOTICE] config option `refused_code_in_responses` is deprecated, use `blocked_query_response`,
> [2019-10-24 20:28:34] [NOTICE] dnscrypt-proxy 2.0.28,
> [2019-10-24 20:28:34] [NOTICE] Network connectivity detected,
> [2019-10-24 20:28:34] [NOTICE] Source [quad9-resolvers.md] loaded,
> [2019-10-24 20:28:34] [NOTICE] Firefox workaround initialized,
> [2019-10-24 20:28:34] [NOTICE] Now listening to 0.0.0.0:5053 [UDP],
> [2019-10-24 20:28:34] [NOTICE] Now listening to 0.0.0.0:5053 [TCP],
> [2019-10-24 20:28:34] [NOTICE] [quad9-dnscrypt-ip4-filter-pri] OK (DNSCrypt) - rtt: 28ms,
> [2019-10-24 20:28:34] [NOTICE] Server with the lowest initial latency: quad9-dnscrypt-ip4-filter-pri (rtt: 28ms),
> [2019-10-24 20:28:34] [NOTICE] dnscrypt-proxy is ready - live servers: 1,

Can you suggest anything?

**Comment by klutchell** [comment] 2019-10-24 20:46
You can try running it with a disabled healthcheck for now. I'll look into it.

```bash
docker create
--name=dnscrypt2
--restart=always
--no-healthcheck
-e PGID=1000 -e PUID=1000
-p 5053:5053/udp
-v /home/pi/docker-dir/dnscrypt/config/:/config:rw
klutchell/dnscrypt-proxy
```

**Comment by adit-s** [comment] 2019-10-24 20:49
Okay.

**Comment by adit-s** [comment] 2019-10-24 21:01
Please ignore the earlier error I mentioned in the logs:

> config option refused_code_in_responses is deprecated, use blocked_query_response

It's not related to this container image.

**Comment by klutchell** [comment] 2019-10-24 22:31
Healthcheck is fixed in the image now. I apologize for the recent issues, there have been a lot of changes in the way I'm securing images this week. Hopefully it will all be worthwhile.

**Comment by adit-s** [comment] 2019-10-26 14:35
Hello. Looks like 2.0.28 is working well. Thanks.

**Closed** 2019-10-26 14:39 UTC
